version: '3.8'
services:
  app:
    container_name: ${PROJECT_NAME:-default}-workspace
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/home/${USERNAME:-vscode}/workspace:cached
    environment:
      USERNAME: ${USERNAME:-vscode}
      USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
      USER_UID: ${USER_UID:-1000}
      USER_GID: ${USER_GID:-1000}
    restart: unless-stopped
    tty: true
    ports:
      - 3000:3000
  redis:
    image: redis:7-alpine
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
